//Publish
export const PUBLISHED = "PUBLISHED";
export const ERROR_ON_PUBLISH = "ERROR_ON_PUBLISHED";
export const RESET_PUBLISH = "RESET_PUBLISH";

//Auth
export const CHECK_USERNAME = "CHECK_USERNAME";
export const CHECK_MAIL = "CHECK_MAIL";
export const RESET_CHECK_USERNAME = "RESET_CHECK_USERNAME";
export const SIGNUP = "SIGNUP";
export const ERROR_ON_SIGNUP = "SIGNUP_ERROR";
export const RESET_SIGNUP = "RESET_SIGNUP";
export const SIGNIN = "SIGNIN";
export const ERROR_ON_SIGNIN = "ERROR_ON_SIGNIN";
export const RESET_SIGNIN = "RESET_SIGNIN";

//Profile
export const MY_STORIES = "MY_STORIES";
export const ERRRO_ON_MY_STORIES = "ERRRO_ON_MY_STORIES";
export const DELETE_STORY = "DELETE_STORY";
export const ERROR_ON_DELETE_STORY = "ERROR_ON_DELETE_STORY";
export const RESET_DELETE_STORY = "RESET_DELETE_STORY";
export const USER_DETAILS = "USER_DETAILS";
export const ERROR_ON_USER_DETAILS = "ERROR_ON_USER_DETAILS";
export const RESET_USER_DETAILS = "RESERT_USER_DETAILS";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const ERROR_ON_UPDATE_PROFILE = "ERROR_ON_UPDATE_PROFILE";
export const RESET_UPDATE_PROFILE = "RESET_UPDATE_PROFILE";

//Search
export const TOP_TAGS = "TOP_TAGS";
export const ERROR_ON_TOP_TAGS = "ERROR_ON_TOP_TAGS";
export const TAG_STORIES = "TAG_STORIES";
export const RESET_TAG_STORIES = "RESET_TAG_STORIES";
export const ERROR_ON_TAG_STORIES = "ERROR_ON_TAG_STORIES";

//UserStories
export const FOLLOWING_STORIES = "FOLLOWING_STORIES";
export const ERROR_ON_FOLLOWING_STORIES = "ERROR_ON_FOLLOWING_STORIES";
export const TOP_STORIES = "TOP_STORIES";
export const ERROR_ON_TOP_STORIES = "ERROR_ON_TOP_STORIES";
export const UNFOLLOW = "UNFOLLOW";
export const ERROR_ON_UNFOLLOW = "ERROR_ON_UNFOLLOW";
export const RESET_UNFOLLOW = "RESET_UNFOLLOW";
